#!/usr/bin/python

import sys,os

raw = "100%"
if len(sys.argv) == 2:
	raw = sys.argv[1]
if raw[-1] == '%':
	raw = raw[:-1]
x = int(raw)

if x < 5 or x > 200:
	print("Percent out of range")
else:
	f = x/100.0
	os.popen('xrandr --output LVDS --brightness %s,%s,%s' % (f,f,f))




	
