#!/usr/bin/bash

# install pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

#install plugins through pathogen
cd ~/.vim/bundle
git clone https://github.com/vimwiki/vimwiki.git

echo "Don't forget to run :Helptags"
